In [1]:
import pandas as pd

In [2]:
# Read in data set
movies_df = pd.read_csv(f'../Resources/movies_metadata.csv')
movies_df.head()

,adult,budget,id,imdb_id,original_language,original_title,overview,release_date,revenue,runtime,status,tagline,title,video,vote_average,vote_count
0,False,30000000,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",10/30/95,373554033.0,81.0,Released,NaN,Toy Story,False,7.7,5415.0
1,False,65000000,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,12/15/95,262797249.0,104.0,Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,0,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,12/22/95,0.0,101.0,Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,16000000,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",12/22/95,81452156.0,127.0,Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,0,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,2/10/95,76578911.0,106.0,Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

The following cell uses a function `more_than_15_words` to select the rows from `movies_df` that have titles with more than 15 words. In the next cell, do the same selection, but using a lambda function

In [3]:
def more_than_15_words(title):
    split_title = title.split() # split the title into a list of words
    number_of_words_in_title = len(split_title) # count the number of words in the title
    is_greater_than_15 = number_of_words_in_title > 15 # check if the number of words is greater than 15
    return is_greater_than_15 # return whether or not the title has more than 15 words

movies_df[movies_df['original_title'].map(more_than_15_words)]

,adult,budget,id,imdb_id,original_language,original_title,overview,release_date,revenue,runtime,status,tagline,title,video,vote_average,vote_count
7241,False,5600000,10338,tt0059797,en,Those Magnificent Men in Their Flying Machines...,Star studded comedy about a early 20th century...,6/3/65,29950000.0,138.0,Released,or How I Flew from London to Paris in 25 hours...,Those Magnificent Men in Their Flying Machines...,False,6.4,40.0
7268,False,0,65332,tt0070061,it,"Film d'amore e d'anarchia, ovvero 'stamattina ...",Set in Fascist Italy before the outbreak of Wo...,2/23/73,0.0,120.0,Released,NaN,Love and Anarchy,False,7.0,8.0
8420,False,0,22638,tt0036910,en,The Chronicle History of King Henry the Fifth ...,Olivier mustered out of the navy to film this ...,11/24/44,0.0,137.0,Released,NaN,Henry V,False,7.0,25.0
9227,False,0,22616,tt0230575,en,Night of the Day of the Dawn of the Son of the...,"The makers of this parody of ""Night of the Liv...",1/1/91,0.0,96.0,Released,NaN,Night of the Day of the Dawn of the Son of the...,False,5.3,4.0
14093,False,0,36108,tt0973844,en,Chacun son cinema ou Ce petit coup au coeur qu...,A collective film of 33 shorts directed by dif...,5/19/07,0.0,100.0,Released,NaN,To Each His Own Cinema,False,7.2,26.0
36823,False,0,270936,tt1023446,en,Ellen ten Damme: As I Was Wondering Where This...,Documentary about Dutch artist Ellen ten Damme...,4/19/07,0.0,66.0,Released,NaN,Ellen ten Damme: As I Was Wondering Where This...,False,0.0,0.0
38508,False,0,132144,tt0072685,es,La batalla de Chile: La lucha de un pueblo sin...,Documents the rise of the right-wing movement ...,3/18/75,0.0,97.0,Released,NaN,The Battle of Chile - Part I,False,6.3,4.0
38511,False,0,132148,tt0074187,es,La batalla de Chile: La lucha de un pueblo sin...,Chronicles the events immediately surrounding ...,3/13/76,0.0,88.0,Released,NaN,The Battle of Chile - Part II,False,6.8,4.0
38512,False,0,132150,tt0078831,es,La batalla de Chile: La lucha de un pueblo sin...,Guzmán’s final instalment shifts from covering...,3/15/79,0.0,78.0,Released,NaN,The Battle of Chile - Part III,False,6.0,3.0
44212,False,0,85854,tt0052156,en,The Saga of the Viking Women and Their Voyage ...,A group of lonely Viking women build a ship an...,12/1/57,0.0,66.0,Released,Fabulous! Spectacular! Terrifying! The raw cou...,The Saga of the Viking Women and Their Voyage ...,False,2.0,3.0

In [4]:
# Find all the movies that have more than 15 words in their title using a lambda function.
movies_df[movies_df['original_title'].map(lambda x: len(x.split())>15)]

,adult,budget,id,imdb_id,original_language,original_title,overview,release_date,revenue,runtime,status,tagline,title,video,vote_average,vote_count
7241,False,5600000,10338,tt0059797,en,Those Magnificent Men in Their Flying Machines...,Star studded comedy about a early 20th century...,6/3/65,29950000.0,138.0,Released,or How I Flew from London to Paris in 25 hours...,Those Magnificent Men in Their Flying Machines...,False,6.4,40.0
7268,False,0,65332,tt0070061,it,"Film d'amore e d'anarchia, ovvero 'stamattina ...",Set in Fascist Italy before the outbreak of Wo...,2/23/73,0.0,120.0,Released,NaN,Love and Anarchy,False,7.0,8.0
8420,False,0,22638,tt0036910,en,The Chronicle History of King Henry the Fifth ...,Olivier mustered out of the navy to film this ...,11/24/44,0.0,137.0,Released,NaN,Henry V,False,7.0,25.0
9227,False,0,22616,tt0230575,en,Night of the Day of the Dawn of the Son of the...,"The makers of this parody of ""Night of the Liv...",1/1/91,0.0,96.0,Released,NaN,Night of the Day of the Dawn of the Son of the...,False,5.3,4.0
14093,False,0,36108,tt0973844,en,Chacun son cinema ou Ce petit coup au coeur qu...,A collective film of 33 shorts directed by dif...,5/19/07,0.0,100.0,Released,NaN,To Each His Own Cinema,False,7.2,26.0
36823,False,0,270936,tt1023446,en,Ellen ten Damme: As I Was Wondering Where This...,Documentary about Dutch artist Ellen ten Damme...,4/19/07,0.0,66.0,Released,NaN,Ellen ten Damme: As I Was Wondering Where This...,False,0.0,0.0
38508,False,0,132144,tt0072685,es,La batalla de Chile: La lucha de un pueblo sin...,Documents the rise of the right-wing movement ...,3/18/75,0.0,97.0,Released,NaN,The Battle of Chile - Part I,False,6.3,4.0
38511,False,0,132148,tt0074187,es,La batalla de Chile: La lucha de un pueblo sin...,Chronicles the events immediately surrounding ...,3/13/76,0.0,88.0,Released,NaN,The Battle of Chile - Part II,False,6.8,4.0
38512,False,0,132150,tt0078831,es,La batalla de Chile: La lucha de un pueblo sin...,Guzmán’s final instalment shifts from covering...,3/15/79,0.0,78.0,Released,NaN,The Battle of Chile - Part III,False,6.0,3.0
44212,False,0,85854,tt0052156,en,The Saga of the Viking Women and Their Voyage ...,A group of lonely Viking women build a ship an...,12/1/57,0.0,66.0,Released,Fabulous! Spectacular! Terrifying! The raw cou...,The Saga of the Viking Women and Their Voyage ...,False,2.0,3.0

In [5]:
def hundredfold_return(row):
    revenue = row['revenue']
    budget = row['budget']
    budget_over_1000 = budget > 1000
    revenue_over_100x = revenue > 100 * budget
    return revenue_over_100x and budget_over_1000
    
movies_df[movies_df.apply(hundredfold_return, axis=1)]

,adult,budget,id,imdb_id,original_language,original_title,overview,release_date,revenue,runtime,status,tagline,title,video,vote_average,vote_count
219,False,27000,2292,tt0109445,en,Clerks,Convenience and video store clerks Dante and R...,9/13/94,3151130.0,92.0,Released,Just because they serve you doesn't mean they ...,Clerks,False,7.4,769.0
587,False,1488423,408,tt0029583,en,Snow White and the Seven Dwarfs,"A beautiful girl, Snow White, takes refuge in ...",12/20/37,184925486.0,83.0,Released,"The Happiest, Dopiest, Grumpiest, Sneeziest mo...",Snow White and the Seven Dwarfs,False,6.9,1973.0
893,False,4000000,770,tt0031381,en,Gone with the Wind,An American classic in which a manipulative wo...,12/15/39,400176459.0,238.0,Released,The greatest romance of all time!,Gone with the Wind,False,7.7,995.0
941,False,114000,10331,tt0063350,en,Night of the Living Dead,A group of people try to survive an attack of ...,10/1/68,30000000.0,96.0,Released,"If it doesn't scare you, you're already dead!",Night of the Living Dead,False,7.5,591.0
1003,False,3000000,12092,tt0043274,en,Alice in Wonderland,"On a golden afternoon, young Alice follows a W...",7/3/51,572000000.0,75.0,Released,A world of wonders in One Great Picture,Alice in Wonderland,False,7.0,1557.0
1845,False,1000000,1366,tt0075148,en,Rocky,"When world heavyweight boxing champion, Apollo...",11/21/76,117235147.0,119.0,Released,His whole life was a million-to-one shot.,Rocky,False,7.5,1843.0
1865,False,550000,4488,tt0080761,en,Friday the 13th,Camp counselors are stalked and murdered by an...,5/9/80,59754601.0,95.0,Released,They were warned...They are doomed...And on Fr...,Friday the 13th,False,6.4,622.0
1873,False,300000,948,tt0077651,en,Halloween,"In John Carpenter's horror classic, a psychoti...",10/25/78,70000000.0,91.0,Released,The Night He Came Home,Halloween,False,7.4,1066.0
1909,False,858000,3170,tt0034492,en,Bambi,Bambi's tale unfolds from season to season as ...,8/14/42,267447150.0,70.0,Released,A great love story.,Bambi,False,6.8,1450.0
2248,False,12000,692,tt0069089,en,Pink Flamingos,Notorious Baltimore criminal and underground f...,3/12/72,6000000.0,93.0,Released,An exercise in poor taste.,Pink Flamingos,False,6.2,111.0
2346,False,85000,30497,tt0072271,en,The Texas Chain Saw Massacre,Five friends visiting their grandfather's hous...,10/1/74,30859000.0,83.0,Released,Who will survive and what will be left of them?,The Texas Chain Saw Massacre,False,7.1,617.0
2595,False,60000,2667,tt0185937,en,The Blair Witch Project,In October of 1994 three student filmmakers di...,7/14/99,248000000.0,81.0,Released,The scariest movie of all time is a true story.,The Blair Witch Project,False,6.3,1090.0
3226,False,24500,28172,tt0056875,en,Blood Feast,"In the sleepy suburbs of Miami, seemingly norm...",6/6/63,4000000.0,67.0,Released,You'll Recoil and Shudder as You Witness the S...,Blood Feast,False,5.3,26.0
3245,False,777000,838,tt0069704,en,American Graffiti,A couple of high school graduates spend one fi...,8/1/73,140000000.0,110.0,Released,Where were you in '62?,American Graffiti,False,6.9,330.0
3554,False,10000,985,tt0074486,en,Eraserhead,Henry Spencer tries to survive his industrial ...,3/19/77,7000000.0,89.0,Released,Where your nightmares end...,Eraserhead,False,7.5,500.0
3580,False,400000,9659,tt0079501,en,Mad Max,"In a dystopian future Australia, a vicious bik...",4/12/79,100000000.0,93.0,Released,The Maximum Force Of The Future,Mad Max,False,6.6,1235.0
4316,False,130000,9462,tt0068935,cn,猛龍過江,Tang Lung arrives in Rome to help his cousins ...,6/1/72,85000000.0,100.0,Released,The Colosseum . . the battleground of Bruce Le...,The Way of the Dragon,False,7.4,235.0
5206,False,106000,46691,tt0065916,en,Joe,"Bill, a wealthy businessman, confronts his jun...",7/15/70,19319254.0,107.0,Released,Keep America Beautiful,Joe,False,5.4,9.0
5340,False,100000,1842,tt0068837,en,The Legend of Boggy Creek,A documentary-style drama based on true accoun...,8/1/72,22000000.0,90.0,Released,A True Story.,The Legend of Boggy Creek,False,5.6,19.0
5452,False,230000,12262,tt0077681,en,The Hills Have Eyes,"On the way to California, a family has the mis...",7/22/77,25000000.0,89.0,Released,A nice American family. They didn't want to ki...,The Hills Have Eyes,False,6.1,145.0
6913,False,100000,618,tt0004972,en,The Birth of a Nation,The Birth of A Nation is a silent film from 19...,2/8/15,11000000.0,193.0,Released,The fiery cross of the Ku Klux Klan.,The Birth of a Nation,False,6.4,109.0
7121,False,70000,29473,tt0073282,en,Let's Do It Again,Clyde Williams and Billy Foster are a couple o...,10/11/75,11800000.0,110.0,Released,"It's the same two dudes from ""Uptown Saturday ...",Let's Do It Again,False,7.7,10.0
7303,False,850000,9461,tt0070034,en,Enter the Dragon,A martial artist agrees to spy on a reclusive ...,8/17/73,90000000.0,99.0,Released,Their deadly mission: to crack the forbidden i...,Enter the Dragon,False,7.3,489.0
7733,False,400000,8193,tt0374900,en,Napoleon Dynamite,A listless and alienated teenager decides to h...,6/11/04,46118097.0,95.0,Released,He's out to prove he's got nothing to prove.,Napoleon Dynamite,False,6.7,567.0
7788,False,65000,9372,tt0390521,en,Super Size Me,Morgan Spurlock subjects himself to a diet bas...,1/17/04,28575078.0,100.0,Released,The first ever reality-based movie ... everyth...,Super Size Me,False,6.6,520.0
8683,False,150000,5822,tt0067810,en,Sweet Sweetback's Baadasssss Song,After saving a Black Panther from some racist ...,4/23/71,15200000.0,97.0,Released,The Film that THE MAN doesn't want you to see!,Sweet Sweetback's Baadasssss Song,False,4.7,19.0
9461,False,130000,83,tt0374102,en,Open Water,Two divers are left out at sea without a boat....,8/6/04,54667954.0,79.0,Released,Scream all you want.,Open Water,False,5.3,320.0
10660,False,169000,9687,tt0444653,en,Keeping Mum,A pastor preoccupied with writing the perfect ...,12/2/05,18564702.0,103.0,Released,Some family secrets are best kept...buried.,Keeping Mum,False,6.5,165.0
11347,False,100000,18925,tt0805526,en,Facing the Giants,A losing coach with an underdog football team ...,9/29/06,10178331.0,111.0,Released,Never give up. Never back down. Never lose faith.,Facing the Giants,False,6.6,64.0
11826,False,160000,5723,tt0907657,en,Once,A vacuum repairman moonlights as a street musi...,3/23/07,20710513.0,85.0,Released,How often do you find the right person?,Once,False,7.4,457.0
14192,False,15000,23827,tt1179904,en,Paranormal Activity,"After a young, middle class couple moves into ...",9/14/07,193355800.0,86.0,Released,What Happens When You Sleep?,Paranormal Activity,False,5.9,1351.0
15898,False,30000,42296,tt1584016,en,Catfish,"Nev, a 24-year-old New York-based photographer...",9/17/10,3045943.0,87.0,Released,Don't let anyone tell you what it is.,Catfish,False,6.5,201.0
18338,False,1000000,76487,tt1560985,en,The Devil Inside,"In Italy, a woman becomes involved in a series...",1/6/12,101758490.0,83.0,Released,No soul is safe.,The Devil Inside,False,4.6,263.0
31626,False,100000,299245,tt2309260,en,The Gallows,20 years after a horrific accident during a sm...,7/10/15,42664410.0,87.0,Released,Every School Has Its Spirit,The Gallows,False,4.9,370.0
41469,False,5000,363093,tt5066556,ko,대호,While the Kingdom of Korea is under occupation...,12/16/15,11083449.0,139.0,Released,NaN,The Tiger: An Old Hunter's Tale,False,7.5,17.0
42305,False,100000,428449,tt6265828,en,A Ghost Story,"Recently deceased, a white-sheeted ghost retur...",7/7/17,15584255.0,92.0,Released,It's all about time,A Ghost Story,False,6.8,95.0

In [6]:
# Find all movies with budgets over 1000 that pulled in revenue over 100x their budget using a lambda function
movies_df[movies_df.apply(lambda row: row['revenue'] > 100 * row['budget'] and row['budget'] > 1000, axis=1)]

,adult,budget,id,imdb_id,original_language,original_title,overview,release_date,revenue,runtime,status,tagline,title,video,vote_average,vote_count
219,False,27000,2292,tt0109445,en,Clerks,Convenience and video store clerks Dante and R...,9/13/94,3151130.0,92.0,Released,Just because they serve you doesn't mean they ...,Clerks,False,7.4,769.0
587,False,1488423,408,tt0029583,en,Snow White and the Seven Dwarfs,"A beautiful girl, Snow White, takes refuge in ...",12/20/37,184925486.0,83.0,Released,"The Happiest, Dopiest, Grumpiest, Sneeziest mo...",Snow White and the Seven Dwarfs,False,6.9,1973.0
893,False,4000000,770,tt0031381,en,Gone with the Wind,An American classic in which a manipulative wo...,12/15/39,400176459.0,238.0,Released,The greatest romance of all time!,Gone with the Wind,False,7.7,995.0
941,False,114000,10331,tt0063350,en,Night of the Living Dead,A group of people try to survive an attack of ...,10/1/68,30000000.0,96.0,Released,"If it doesn't scare you, you're already dead!",Night of the Living Dead,False,7.5,591.0
1003,False,3000000,12092,tt0043274,en,Alice in Wonderland,"On a golden afternoon, young Alice follows a W...",7/3/51,572000000.0,75.0,Released,A world of wonders in One Great Picture,Alice in Wonderland,False,7.0,1557.0
1845,False,1000000,1366,tt0075148,en,Rocky,"When world heavyweight boxing champion, Apollo...",11/21/76,117235147.0,119.0,Released,His whole life was a million-to-one shot.,Rocky,False,7.5,1843.0
1865,False,550000,4488,tt0080761,en,Friday the 13th,Camp counselors are stalked and murdered by an...,5/9/80,59754601.0,95.0,Released,They were warned...They are doomed...And on Fr...,Friday the 13th,False,6.4,622.0
1873,False,300000,948,tt0077651,en,Halloween,"In John Carpenter's horror classic, a psychoti...",10/25/78,70000000.0,91.0,Released,The Night He Came Home,Halloween,False,7.4,1066.0
1909,False,858000,3170,tt0034492,en,Bambi,Bambi's tale unfolds from season to season as ...,8/14/42,267447150.0,70.0,Released,A great love story.,Bambi,False,6.8,1450.0
2248,False,12000,692,tt0069089,en,Pink Flamingos,Notorious Baltimore criminal and underground f...,3/12/72,6000000.0,93.0,Released,An exercise in poor taste.,Pink Flamingos,False,6.2,111.0
2346,False,85000,30497,tt0072271,en,The Texas Chain Saw Massacre,Five friends visiting their grandfather's hous...,10/1/74,30859000.0,83.0,Released,Who will survive and what will be left of them?,The Texas Chain Saw Massacre,False,7.1,617.0
2595,False,60000,2667,tt0185937,en,The Blair Witch Project,In October of 1994 three student filmmakers di...,7/14/99,248000000.0,81.0,Released,The scariest movie of all time is a true story.,The Blair Witch Project,False,6.3,1090.0
3226,False,24500,28172,tt0056875,en,Blood Feast,"In the sleepy suburbs of Miami, seemingly norm...",6/6/63,4000000.0,67.0,Released,You'll Recoil and Shudder as You Witness the S...,Blood Feast,False,5.3,26.0
3245,False,777000,838,tt0069704,en,American Graffiti,A couple of high school graduates spend one fi...,8/1/73,140000000.0,110.0,Released,Where were you in '62?,American Graffiti,False,6.9,330.0
3554,False,10000,985,tt0074486,en,Eraserhead,Henry Spencer tries to survive his industrial ...,3/19/77,7000000.0,89.0,Released,Where your nightmares end...,Eraserhead,False,7.5,500.0
3580,False,400000,9659,tt0079501,en,Mad Max,"In a dystopian future Australia, a vicious bik...",4/12/79,100000000.0,93.0,Released,The Maximum Force Of The Future,Mad Max,False,6.6,1235.0
4316,False,130000,9462,tt0068935,cn,猛龍過江,Tang Lung arrives in Rome to help his cousins ...,6/1/72,85000000.0,100.0,Released,The Colosseum . . the battleground of Bruce Le...,The Way of the Dragon,False,7.4,235.0
5206,False,106000,46691,tt0065916,en,Joe,"Bill, a wealthy businessman, confronts his jun...",7/15/70,19319254.0,107.0,Released,Keep America Beautiful,Joe,False,5.4,9.0
5340,False,100000,1842,tt0068837,en,The Legend of Boggy Creek,A documentary-style drama based on true accoun...,8/1/72,22000000.0,90.0,Released,A True Story.,The Legend of Boggy Creek,False,5.6,19.0
5452,False,230000,12262,tt0077681,en,The Hills Have Eyes,"On the way to California, a family has the mis...",7/22/77,25000000.0,89.0,Released,A nice American family. They didn't want to ki...,The Hills Have Eyes,False,6.1,145.0
6913,False,100000,618,tt0004972,en,The Birth of a Nation,The Birth of A Nation is a silent film from 19...,2/8/15,11000000.0,193.0,Released,The fiery cross of the Ku Klux Klan.,The Birth of a Nation,False,6.4,109.0
7121,False,70000,29473,tt0073282,en,Let's Do It Again,Clyde Williams and Billy Foster are a couple o...,10/11/75,11800000.0,110.0,Released,"It's the same two dudes from ""Uptown Saturday ...",Let's Do It Again,False,7.7,10.0
7303,False,850000,9461,tt0070034,en,Enter the Dragon,A martial artist agrees to spy on a reclusive ...,8/17/73,90000000.0,99.0,Released,Their deadly mission: to crack the forbidden i...,Enter the Dragon,False,7.3,489.0
7733,False,400000,8193,tt0374900,en,Napoleon Dynamite,A listless and alienated teenager decides to h...,6/11/04,46118097.0,95.0,Released,He's out to prove he's got nothing to prove.,Napoleon Dynamite,False,6.7,567.0
7788,False,65000,9372,tt0390521,en,Super Size Me,Morgan Spurlock subjects himself to a diet bas...,1/17/04,28575078.0,100.0,Released,The first ever reality-based movie ... everyth...,Super Size Me,False,6.6,520.0
8683,False,150000,5822,tt0067810,en,Sweet Sweetback's Baadasssss Song,After saving a Black Panther from some racist ...,4/23/71,15200000.0,97.0,Released,The Film that THE MAN doesn't want you to see!,Sweet Sweetback's Baadasssss Song,False,4.7,19.0
9461,False,130000,83,tt0374102,en,Open Water,Two divers are left out at sea without a boat....,8/6/04,54667954.0,79.0,Released,Scream all you want.,Open Water,False,5.3,320.0
10660,False,169000,9687,tt0444653,en,Keeping Mum,A pastor preoccupied with writing the perfect ...,12/2/05,18564702.0,103.0,Released,Some family secrets are best kept...buried.,Keeping Mum,False,6.5,165.0
11347,False,100000,18925,tt0805526,en,Facing the Giants,A losing coach with an underdog football team ...,9/29/06,10178331.0,111.0,Released,Never give up. Never back down. Never lose faith.,Facing the Giants,False,6.6,64.0
11826,False,160000,5723,tt0907657,en,Once,A vacuum repairman moonlights as a street musi...,3/23/07,20710513.0,85.0,Released,How often do you find the right person?,Once,False,7.4,457.0
14192,False,15000,23827,tt1179904,en,Paranormal Activity,"After a young, middle class couple moves into ...",9/14/07,193355800.0,86.0,Released,What Happens When You Sleep?,Paranormal Activity,False,5.9,1351.0
15898,False,30000,42296,tt1584016,en,Catfish,"Nev, a 24-year-old New York-based photographer...",9/17/10,3045943.0,87.0,Released,Don't let anyone tell you what it is.,Catfish,False,6.5,201.0
18338,False,1000000,76487,tt1560985,en,The Devil Inside,"In Italy, a woman becomes involved in a series...",1/6/12,101758490.0,83.0,Released,No soul is safe.,The Devil Inside,False,4.6,263.0
31626,False,100000,299245,tt2309260,en,The Gallows,20 years after a horrific accident during a sm...,7/10/15,42664410.0,87.0,Released,Every School Has Its Spirit,The Gallows,False,4.9,370.0
41469,False,5000,363093,tt5066556,ko,대호,While the Kingdom of Korea is under occupation...,12/16/15,11083449.0,139.0,Released,NaN,The Tiger: An Old Hunter's Tale,False,7.5,17.0
42305,False,100000,428449,tt6265828,en,A Ghost Story,"Recently deceased, a white-sheeted ghost retur...",7/7/17,15584255.0,92.0,Released,It's all about time,A Ghost Story,False,6.8,95.0

In [7]:
# load in list of English words
words_file = '../Resources/words.txt'

words_df = pd.read_csv(words_file, sep='\n', header=None)
words_df.columns = ['text']
words_df.head()

  text
0  the
1   of
2  and
3   to
4    a

In [8]:
def contains_x(word):
    split_word = list(word)
    word_contains_x = 'x' in split_word
    return word_contains_x

words_df[words_df['text'].map(contains_x)]

              text
97               x
120           next
274          index
347           text
449            box
...            ...
9748       expects
9759  examinations
9791       halifax
9808      examines
9872      lightbox

[246 rows x 1 columns]

In [9]:
# Find all words containing the letter 'x' using a lambda function
words_df[words_df['text'].map(lambda word: 'x' in list(word))]

              text
97               x
120           next
274          index
347           text
449            box
...            ...
9748       expects
9759  examinations
9791       halifax
9808      examines
9872      lightbox

[246 rows x 1 columns]